### ISSUE TITLE
Add Ability to share specific content from the site and like: WebsiteURL#section

### ISSUE THREAD

**Issue by 4tal** [4tal/LinksForIsrael#50]

**Comment by ohadschn** [comment]
Before closing this, let's replace the `Share` string with a share icon

**Comment by ohadschn** [comment]
1. Ideally this could be a "true" share that opens up options for apps/sites (e.g. WhatsApp, mail) where there's a special option to copy the link (in other words, the current functionality would be a special case of the general sharing experience)
2. The shared link doesn't expand the relevant section, and you don't even know if you copied the right one because there's no status bar indication of the URL (it's JS that copied the link to the clipboard directly).
